stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/playwright/java:v1.44.0-jammy
  script:
    - mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    - mvn test
  artifacts:
    paths:
      - playwright-report/
    reports:
      junit: playwright-report/*.xml
    when: always
    expire_in: 30 mins
